version: '3'

services:
  frontend-app:
    build: ./frontend
    volumes:
      - ./frontend:/app
    image: frontend-app
    container_name: frontend-app
    ports:
      - '5000:5000'
  backend-app:
    build: ./backend
    volumes:
      - ./backend:/app
    image: backend-app
    container_name: backend-app
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    logging:
      driver: none
